# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import air_traffic_types_pb2 as air__traffic__types__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in air_traffic_types_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AircraftServiceStub(object):
    """─── gRPC Service Definitions ──────────────────────────────
    Each application that produces data runs its own gRPC server.
    Consumers connect directly to the servers they need.

    AircraftService — hosted by each airplane process.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamPositions = channel.unary_stream(
                '/national_air_traffic_control.AircraftService/StreamPositions',
                request_serializer=air__traffic__types__pb2.EmptyFilter.SerializeToString,
                response_deserializer=air__traffic__types__pb2.AircraftPosition.FromString,
                _registered_method=True)
        self.StreamAcknowledgments = channel.unary_stream(
                '/national_air_traffic_control.AircraftService/StreamAcknowledgments',
                request_serializer=air__traffic__types__pb2.EmptyFilter.SerializeToString,
                response_deserializer=air__traffic__types__pb2.PilotAcknowledgment.FromString,
                _registered_method=True)


class AircraftServiceServicer(object):
    """─── gRPC Service Definitions ──────────────────────────────
    Each application that produces data runs its own gRPC server.
    Consumers connect directly to the servers they need.

    AircraftService — hosted by each airplane process.
    """

    def StreamPositions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamAcknowledgments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AircraftServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamPositions': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamPositions,
                    request_deserializer=air__traffic__types__pb2.EmptyFilter.FromString,
                    response_serializer=air__traffic__types__pb2.AircraftPosition.SerializeToString,
            ),
            'StreamAcknowledgments': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamAcknowledgments,
                    request_deserializer=air__traffic__types__pb2.EmptyFilter.FromString,
                    response_serializer=air__traffic__types__pb2.PilotAcknowledgment.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'national_air_traffic_control.AircraftService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('national_air_traffic_control.AircraftService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AircraftService(object):
    """─── gRPC Service Definitions ──────────────────────────────
    Each application that produces data runs its own gRPC server.
    Consumers connect directly to the servers they need.

    AircraftService — hosted by each airplane process.
    """

    @staticmethod
    def StreamPositions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/national_air_traffic_control.AircraftService/StreamPositions',
            air__traffic__types__pb2.EmptyFilter.SerializeToString,
            air__traffic__types__pb2.AircraftPosition.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamAcknowledgments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/national_air_traffic_control.AircraftService/StreamAcknowledgments',
            air__traffic__types__pb2.EmptyFilter.SerializeToString,
            air__traffic__types__pb2.PilotAcknowledgment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TowerServiceStub(object):
    """TowerService — hosted by each control tower.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamInstructions = channel.unary_stream(
                '/national_air_traffic_control.TowerService/StreamInstructions',
                request_serializer=air__traffic__types__pb2.ControllerInstructionFilter.SerializeToString,
                response_deserializer=air__traffic__types__pb2.ControllerInstruction.FromString,
                _registered_method=True)
        self.StreamHandoffs = channel.unary_stream(
                '/national_air_traffic_control.TowerService/StreamHandoffs',
                request_serializer=air__traffic__types__pb2.HandoffFilter.SerializeToString,
                response_deserializer=air__traffic__types__pb2.Handoff.FromString,
                _registered_method=True)
        self.StreamAlerts = channel.unary_stream(
                '/national_air_traffic_control.TowerService/StreamAlerts',
                request_serializer=air__traffic__types__pb2.EmptyFilter.SerializeToString,
                response_deserializer=air__traffic__types__pb2.Alert.FromString,
                _registered_method=True)
        self.StreamTracking = channel.unary_stream(
                '/national_air_traffic_control.TowerService/StreamTracking',
                request_serializer=air__traffic__types__pb2.EmptyFilter.SerializeToString,
                response_deserializer=air__traffic__types__pb2.AircraftTracking.FromString,
                _registered_method=True)
        self.StreamFacilityStatus = channel.unary_stream(
                '/national_air_traffic_control.TowerService/StreamFacilityStatus',
                request_serializer=air__traffic__types__pb2.EmptyFilter.SerializeToString,
                response_deserializer=air__traffic__types__pb2.FacilityStatus.FromString,
                _registered_method=True)
        self.StreamRunwayStatus = channel.unary_stream(
                '/national_air_traffic_control.TowerService/StreamRunwayStatus',
                request_serializer=air__traffic__types__pb2.EmptyFilter.SerializeToString,
                response_deserializer=air__traffic__types__pb2.RunwayStatus.FromString,
                _registered_method=True)
        self.SendHandoff = channel.unary_unary(
                '/national_air_traffic_control.TowerService/SendHandoff',
                request_serializer=air__traffic__types__pb2.Handoff.SerializeToString,
                response_deserializer=air__traffic__types__pb2.HandoffAck.FromString,
                _registered_method=True)


class TowerServiceServicer(object):
    """TowerService — hosted by each control tower.
    """

    def StreamInstructions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamHandoffs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamAlerts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTracking(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamFacilityStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamRunwayStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendHandoff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TowerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamInstructions': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamInstructions,
                    request_deserializer=air__traffic__types__pb2.ControllerInstructionFilter.FromString,
                    response_serializer=air__traffic__types__pb2.ControllerInstruction.SerializeToString,
            ),
            'StreamHandoffs': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamHandoffs,
                    request_deserializer=air__traffic__types__pb2.HandoffFilter.FromString,
                    response_serializer=air__traffic__types__pb2.Handoff.SerializeToString,
            ),
            'StreamAlerts': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamAlerts,
                    request_deserializer=air__traffic__types__pb2.EmptyFilter.FromString,
                    response_serializer=air__traffic__types__pb2.Alert.SerializeToString,
            ),
            'StreamTracking': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTracking,
                    request_deserializer=air__traffic__types__pb2.EmptyFilter.FromString,
                    response_serializer=air__traffic__types__pb2.AircraftTracking.SerializeToString,
            ),
            'StreamFacilityStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamFacilityStatus,
                    request_deserializer=air__traffic__types__pb2.EmptyFilter.FromString,
                    response_serializer=air__traffic__types__pb2.FacilityStatus.SerializeToString,
            ),
            'StreamRunwayStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamRunwayStatus,
                    request_deserializer=air__traffic__types__pb2.EmptyFilter.FromString,
                    response_serializer=air__traffic__types__pb2.RunwayStatus.SerializeToString,
            ),
            'SendHandoff': grpc.unary_unary_rpc_method_handler(
                    servicer.SendHandoff,
                    request_deserializer=air__traffic__types__pb2.Handoff.FromString,
                    response_serializer=air__traffic__types__pb2.HandoffAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'national_air_traffic_control.TowerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('national_air_traffic_control.TowerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TowerService(object):
    """TowerService — hosted by each control tower.
    """

    @staticmethod
    def StreamInstructions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/national_air_traffic_control.TowerService/StreamInstructions',
            air__traffic__types__pb2.ControllerInstructionFilter.SerializeToString,
            air__traffic__types__pb2.ControllerInstruction.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamHandoffs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/national_air_traffic_control.TowerService/StreamHandoffs',
            air__traffic__types__pb2.HandoffFilter.SerializeToString,
            air__traffic__types__pb2.Handoff.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamAlerts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/national_air_traffic_control.TowerService/StreamAlerts',
            air__traffic__types__pb2.EmptyFilter.SerializeToString,
            air__traffic__types__pb2.Alert.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTracking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/national_air_traffic_control.TowerService/StreamTracking',
            air__traffic__types__pb2.EmptyFilter.SerializeToString,
            air__traffic__types__pb2.AircraftTracking.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamFacilityStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/national_air_traffic_control.TowerService/StreamFacilityStatus',
            air__traffic__types__pb2.EmptyFilter.SerializeToString,
            air__traffic__types__pb2.FacilityStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamRunwayStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/national_air_traffic_control.TowerService/StreamRunwayStatus',
            air__traffic__types__pb2.EmptyFilter.SerializeToString,
            air__traffic__types__pb2.RunwayStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendHandoff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/national_air_traffic_control.TowerService/SendHandoff',
            air__traffic__types__pb2.Handoff.SerializeToString,
            air__traffic__types__pb2.HandoffAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TraconServiceStub(object):
    """TraconService — hosted by each TRACON facility.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamInstructions = channel.unary_stream(
                '/national_air_traffic_control.TraconService/StreamInstructions',
                request_serializer=air__traffic__types__pb2.ControllerInstructionFilter.SerializeToString,
                response_deserializer=air__traffic__types__pb2.ControllerInstruction.FromString,
                _registered_method=True)
        self.StreamHandoffs = channel.unary_stream(
                '/national_air_traffic_control.TraconService/StreamHandoffs',
                request_serializer=air__traffic__types__pb2.HandoffFilter.SerializeToString,
                response_deserializer=air__traffic__types__pb2.Handoff.FromString,
                _registered_method=True)
        self.StreamAlerts = channel.unary_stream(
                '/national_air_traffic_control.TraconService/StreamAlerts',
                request_serializer=air__traffic__types__pb2.EmptyFilter.SerializeToString,
                response_deserializer=air__traffic__types__pb2.Alert.FromString,
                _registered_method=True)
        self.StreamTracking = channel.unary_stream(
                '/national_air_traffic_control.TraconService/StreamTracking',
                request_serializer=air__traffic__types__pb2.EmptyFilter.SerializeToString,
                response_deserializer=air__traffic__types__pb2.AircraftTracking.FromString,
                _registered_method=True)
        self.StreamFacilityStatus = channel.unary_stream(
                '/national_air_traffic_control.TraconService/StreamFacilityStatus',
                request_serializer=air__traffic__types__pb2.EmptyFilter.SerializeToString,
                response_deserializer=air__traffic__types__pb2.FacilityStatus.FromString,
                _registered_method=True)
        self.SendHandoff = channel.unary_unary(
                '/national_air_traffic_control.TraconService/SendHandoff',
                request_serializer=air__traffic__types__pb2.Handoff.SerializeToString,
                response_deserializer=air__traffic__types__pb2.HandoffAck.FromString,
                _registered_method=True)


class TraconServiceServicer(object):
    """TraconService — hosted by each TRACON facility.
    """

    def StreamInstructions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamHandoffs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamAlerts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTracking(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamFacilityStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendHandoff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TraconServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamInstructions': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamInstructions,
                    request_deserializer=air__traffic__types__pb2.ControllerInstructionFilter.FromString,
                    response_serializer=air__traffic__types__pb2.ControllerInstruction.SerializeToString,
            ),
            'StreamHandoffs': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamHandoffs,
                    request_deserializer=air__traffic__types__pb2.HandoffFilter.FromString,
                    response_serializer=air__traffic__types__pb2.Handoff.SerializeToString,
            ),
            'StreamAlerts': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamAlerts,
                    request_deserializer=air__traffic__types__pb2.EmptyFilter.FromString,
                    response_serializer=air__traffic__types__pb2.Alert.SerializeToString,
            ),
            'StreamTracking': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTracking,
                    request_deserializer=air__traffic__types__pb2.EmptyFilter.FromString,
                    response_serializer=air__traffic__types__pb2.AircraftTracking.SerializeToString,
            ),
            'StreamFacilityStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamFacilityStatus,
                    request_deserializer=air__traffic__types__pb2.EmptyFilter.FromString,
                    response_serializer=air__traffic__types__pb2.FacilityStatus.SerializeToString,
            ),
            'SendHandoff': grpc.unary_unary_rpc_method_handler(
                    servicer.SendHandoff,
                    request_deserializer=air__traffic__types__pb2.Handoff.FromString,
                    response_serializer=air__traffic__types__pb2.HandoffAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'national_air_traffic_control.TraconService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('national_air_traffic_control.TraconService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TraconService(object):
    """TraconService — hosted by each TRACON facility.
    """

    @staticmethod
    def StreamInstructions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/national_air_traffic_control.TraconService/StreamInstructions',
            air__traffic__types__pb2.ControllerInstructionFilter.SerializeToString,
            air__traffic__types__pb2.ControllerInstruction.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamHandoffs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/national_air_traffic_control.TraconService/StreamHandoffs',
            air__traffic__types__pb2.HandoffFilter.SerializeToString,
            air__traffic__types__pb2.Handoff.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamAlerts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/national_air_traffic_control.TraconService/StreamAlerts',
            air__traffic__types__pb2.EmptyFilter.SerializeToString,
            air__traffic__types__pb2.Alert.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTracking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/national_air_traffic_control.TraconService/StreamTracking',
            air__traffic__types__pb2.EmptyFilter.SerializeToString,
            air__traffic__types__pb2.AircraftTracking.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamFacilityStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/national_air_traffic_control.TraconService/StreamFacilityStatus',
            air__traffic__types__pb2.EmptyFilter.SerializeToString,
            air__traffic__types__pb2.FacilityStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendHandoff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/national_air_traffic_control.TraconService/SendHandoff',
            air__traffic__types__pb2.Handoff.SerializeToString,
            air__traffic__types__pb2.HandoffAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CenterServiceStub(object):
    """CenterService — hosted by each en-route center.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamInstructions = channel.unary_stream(
                '/national_air_traffic_control.CenterService/StreamInstructions',
                request_serializer=air__traffic__types__pb2.ControllerInstructionFilter.SerializeToString,
                response_deserializer=air__traffic__types__pb2.ControllerInstruction.FromString,
                _registered_method=True)
        self.StreamHandoffs = channel.unary_stream(
                '/national_air_traffic_control.CenterService/StreamHandoffs',
                request_serializer=air__traffic__types__pb2.HandoffFilter.SerializeToString,
                response_deserializer=air__traffic__types__pb2.Handoff.FromString,
                _registered_method=True)
        self.StreamAlerts = channel.unary_stream(
                '/national_air_traffic_control.CenterService/StreamAlerts',
                request_serializer=air__traffic__types__pb2.EmptyFilter.SerializeToString,
                response_deserializer=air__traffic__types__pb2.Alert.FromString,
                _registered_method=True)
        self.StreamTracking = channel.unary_stream(
                '/national_air_traffic_control.CenterService/StreamTracking',
                request_serializer=air__traffic__types__pb2.EmptyFilter.SerializeToString,
                response_deserializer=air__traffic__types__pb2.AircraftTracking.FromString,
                _registered_method=True)
        self.StreamFacilityStatus = channel.unary_stream(
                '/national_air_traffic_control.CenterService/StreamFacilityStatus',
                request_serializer=air__traffic__types__pb2.EmptyFilter.SerializeToString,
                response_deserializer=air__traffic__types__pb2.FacilityStatus.FromString,
                _registered_method=True)
        self.SendHandoff = channel.unary_unary(
                '/national_air_traffic_control.CenterService/SendHandoff',
                request_serializer=air__traffic__types__pb2.Handoff.SerializeToString,
                response_deserializer=air__traffic__types__pb2.HandoffAck.FromString,
                _registered_method=True)


class CenterServiceServicer(object):
    """CenterService — hosted by each en-route center.
    """

    def StreamInstructions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamHandoffs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamAlerts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTracking(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamFacilityStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendHandoff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CenterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamInstructions': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamInstructions,
                    request_deserializer=air__traffic__types__pb2.ControllerInstructionFilter.FromString,
                    response_serializer=air__traffic__types__pb2.ControllerInstruction.SerializeToString,
            ),
            'StreamHandoffs': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamHandoffs,
                    request_deserializer=air__traffic__types__pb2.HandoffFilter.FromString,
                    response_serializer=air__traffic__types__pb2.Handoff.SerializeToString,
            ),
            'StreamAlerts': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamAlerts,
                    request_deserializer=air__traffic__types__pb2.EmptyFilter.FromString,
                    response_serializer=air__traffic__types__pb2.Alert.SerializeToString,
            ),
            'StreamTracking': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTracking,
                    request_deserializer=air__traffic__types__pb2.EmptyFilter.FromString,
                    response_serializer=air__traffic__types__pb2.AircraftTracking.SerializeToString,
            ),
            'StreamFacilityStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamFacilityStatus,
                    request_deserializer=air__traffic__types__pb2.EmptyFilter.FromString,
                    response_serializer=air__traffic__types__pb2.FacilityStatus.SerializeToString,
            ),
            'SendHandoff': grpc.unary_unary_rpc_method_handler(
                    servicer.SendHandoff,
                    request_deserializer=air__traffic__types__pb2.Handoff.FromString,
                    response_serializer=air__traffic__types__pb2.HandoffAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'national_air_traffic_control.CenterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('national_air_traffic_control.CenterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CenterService(object):
    """CenterService — hosted by each en-route center.
    """

    @staticmethod
    def StreamInstructions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/national_air_traffic_control.CenterService/StreamInstructions',
            air__traffic__types__pb2.ControllerInstructionFilter.SerializeToString,
            air__traffic__types__pb2.ControllerInstruction.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamHandoffs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/national_air_traffic_control.CenterService/StreamHandoffs',
            air__traffic__types__pb2.HandoffFilter.SerializeToString,
            air__traffic__types__pb2.Handoff.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamAlerts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/national_air_traffic_control.CenterService/StreamAlerts',
            air__traffic__types__pb2.EmptyFilter.SerializeToString,
            air__traffic__types__pb2.Alert.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTracking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/national_air_traffic_control.CenterService/StreamTracking',
            air__traffic__types__pb2.EmptyFilter.SerializeToString,
            air__traffic__types__pb2.AircraftTracking.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamFacilityStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/national_air_traffic_control.CenterService/StreamFacilityStatus',
            air__traffic__types__pb2.EmptyFilter.SerializeToString,
            air__traffic__types__pb2.FacilityStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendHandoff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/national_air_traffic_control.CenterService/SendHandoff',
            air__traffic__types__pb2.Handoff.SerializeToString,
            air__traffic__types__pb2.HandoffAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AirportServiceStub(object):
    """AirportService — hosted by each airport.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamWeatherReports = channel.unary_stream(
                '/national_air_traffic_control.AirportService/StreamWeatherReports',
                request_serializer=air__traffic__types__pb2.WeatherReportFilter.SerializeToString,
                response_deserializer=air__traffic__types__pb2.WeatherReport.FromString,
                _registered_method=True)
        self.StreamRunwayStatus = channel.unary_stream(
                '/national_air_traffic_control.AirportService/StreamRunwayStatus',
                request_serializer=air__traffic__types__pb2.EmptyFilter.SerializeToString,
                response_deserializer=air__traffic__types__pb2.RunwayStatus.FromString,
                _registered_method=True)
        self.RequestGate = channel.unary_stream(
                '/national_air_traffic_control.AirportService/RequestGate',
                request_serializer=air__traffic__types__pb2.GateRequest.SerializeToString,
                response_deserializer=air__traffic__types__pb2.GateAssignmentReply.FromString,
                _registered_method=True)


class AirportServiceServicer(object):
    """AirportService — hosted by each airport.
    """

    def StreamWeatherReports(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamRunwayStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestGate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AirportServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamWeatherReports': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamWeatherReports,
                    request_deserializer=air__traffic__types__pb2.WeatherReportFilter.FromString,
                    response_serializer=air__traffic__types__pb2.WeatherReport.SerializeToString,
            ),
            'StreamRunwayStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamRunwayStatus,
                    request_deserializer=air__traffic__types__pb2.EmptyFilter.FromString,
                    response_serializer=air__traffic__types__pb2.RunwayStatus.SerializeToString,
            ),
            'RequestGate': grpc.unary_stream_rpc_method_handler(
                    servicer.RequestGate,
                    request_deserializer=air__traffic__types__pb2.GateRequest.FromString,
                    response_serializer=air__traffic__types__pb2.GateAssignmentReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'national_air_traffic_control.AirportService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('national_air_traffic_control.AirportService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AirportService(object):
    """AirportService — hosted by each airport.
    """

    @staticmethod
    def StreamWeatherReports(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/national_air_traffic_control.AirportService/StreamWeatherReports',
            air__traffic__types__pb2.WeatherReportFilter.SerializeToString,
            air__traffic__types__pb2.WeatherReport.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamRunwayStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/national_air_traffic_control.AirportService/StreamRunwayStatus',
            air__traffic__types__pb2.EmptyFilter.SerializeToString,
            air__traffic__types__pb2.RunwayStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestGate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/national_air_traffic_control.AirportService/RequestGate',
            air__traffic__types__pb2.GateRequest.SerializeToString,
            air__traffic__types__pb2.GateAssignmentReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class FlightPlanServiceStub(object):
    """FlightPlanService — single standalone server for flight plan filing.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FileFlightPlan = channel.unary_unary(
                '/national_air_traffic_control.FlightPlanService/FileFlightPlan',
                request_serializer=air__traffic__types__pb2.FlightPlanRequest.SerializeToString,
                response_deserializer=air__traffic__types__pb2.FlightPlanResponse.FromString,
                _registered_method=True)
        self.StreamFlightPlans = channel.unary_stream(
                '/national_air_traffic_control.FlightPlanService/StreamFlightPlans',
                request_serializer=air__traffic__types__pb2.EmptyFilter.SerializeToString,
                response_deserializer=air__traffic__types__pb2.FlightPlan.FromString,
                _registered_method=True)


class FlightPlanServiceServicer(object):
    """FlightPlanService — single standalone server for flight plan filing.
    """

    def FileFlightPlan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamFlightPlans(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FlightPlanServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FileFlightPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.FileFlightPlan,
                    request_deserializer=air__traffic__types__pb2.FlightPlanRequest.FromString,
                    response_serializer=air__traffic__types__pb2.FlightPlanResponse.SerializeToString,
            ),
            'StreamFlightPlans': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamFlightPlans,
                    request_deserializer=air__traffic__types__pb2.EmptyFilter.FromString,
                    response_serializer=air__traffic__types__pb2.FlightPlan.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'national_air_traffic_control.FlightPlanService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('national_air_traffic_control.FlightPlanService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FlightPlanService(object):
    """FlightPlanService — single standalone server for flight plan filing.
    """

    @staticmethod
    def FileFlightPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/national_air_traffic_control.FlightPlanService/FileFlightPlan',
            air__traffic__types__pb2.FlightPlanRequest.SerializeToString,
            air__traffic__types__pb2.FlightPlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamFlightPlans(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/national_air_traffic_control.FlightPlanService/StreamFlightPlans',
            air__traffic__types__pb2.EmptyFilter.SerializeToString,
            air__traffic__types__pb2.FlightPlan.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WeatherServiceStub(object):
    """WeatherService — single standalone server for en-route weather.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamConvectiveCells = channel.unary_stream(
                '/national_air_traffic_control.WeatherService/StreamConvectiveCells',
                request_serializer=air__traffic__types__pb2.EmptyFilter.SerializeToString,
                response_deserializer=air__traffic__types__pb2.ConvectiveCell.FromString,
                _registered_method=True)
        self.InjectCell = channel.unary_unary(
                '/national_air_traffic_control.WeatherService/InjectCell',
                request_serializer=air__traffic__types__pb2.ConvectiveCell.SerializeToString,
                response_deserializer=air__traffic__types__pb2.CellInjectionAck.FromString,
                _registered_method=True)


class WeatherServiceServicer(object):
    """WeatherService — single standalone server for en-route weather.
    """

    def StreamConvectiveCells(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InjectCell(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WeatherServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamConvectiveCells': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamConvectiveCells,
                    request_deserializer=air__traffic__types__pb2.EmptyFilter.FromString,
                    response_serializer=air__traffic__types__pb2.ConvectiveCell.SerializeToString,
            ),
            'InjectCell': grpc.unary_unary_rpc_method_handler(
                    servicer.InjectCell,
                    request_deserializer=air__traffic__types__pb2.ConvectiveCell.FromString,
                    response_serializer=air__traffic__types__pb2.CellInjectionAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'national_air_traffic_control.WeatherService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('national_air_traffic_control.WeatherService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WeatherService(object):
    """WeatherService — single standalone server for en-route weather.
    """

    @staticmethod
    def StreamConvectiveCells(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/national_air_traffic_control.WeatherService/StreamConvectiveCells',
            air__traffic__types__pb2.EmptyFilter.SerializeToString,
            air__traffic__types__pb2.ConvectiveCell.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InjectCell(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/national_air_traffic_control.WeatherService/InjectCell',
            air__traffic__types__pb2.ConvectiveCell.SerializeToString,
            air__traffic__types__pb2.CellInjectionAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
